<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $img = fn (string $file) => "/images/destinations/{$file}";

        $destinations = [
            [
                'name' => 'Maasai Mara National Reserve',
                'slug' => 'maasai-mara',
                'region' => 'Narok County',
                'location' => 'Narok County, South-West Kenya',
                'region_key' => 'south',
                'tag' => 'The Great Migration',
                'best_time' => 'Jul – Oct',
                'image' => $img('maasai-mara.png'),
                'hero_image' => $img('maasai-mara.png'),
                'excerpt' => 'Kenya\'s most famous safari destination — abundant wildlife, vast savannahs, and the spectacular Great Migration.',
                'intro' => 'Masai Mara National Reserve is Kenya\'s most famous safari destination, renowned for its abundant wildlife, vast savannahs, and the spectacular Great Migration.',
                'description' => 'Famous for the Great Migration, Big Five, and exceptional game viewing. Rolling savannah stretches to the horizon, broken by acacia trees and the Mara River. From July to October, wildebeest, zebra and gazelle move through on one of the last great wildlife spectacles on Earth. Year-round, the Mara offers outstanding opportunities to see lions, leopards, cheetahs, elephants, buffaloes and rich birdlife.',
                'activities' => ['Big Five Game Drives', 'Great Migration Viewing', 'Hot Air Balloon Safari', 'Maasai Cultural Visits', 'Photography'],
                'gallery' => [
                    $img('maasai-mara-balloons.png'),
                    $img('maasai-mara-migration.png'),
                    $img('maasai-mara-safari.png'),
                    $img('maasai-mara-balloon.png'),
                ],
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Amboseli National Park',
                'slug' => 'amboseli',
                'region' => 'Kajiado County',
                'location' => 'Kajiado County',
                'region_key' => 'south',
                'tag' => 'Beneath Kilimanjaro',
                'best_time' => 'Jun – Oct',
                'image' => $img('amboseli.png'),
                'hero_image' => $img('amboseli.png'),
                'excerpt' => 'Large elephant herds set against the snow-capped peak of Mount Kilimanjaro — one of Kenya\'s most photogenic parks.',
                'intro' => 'Amboseli National Park is one of Kenya\'s most photogenic safari destinations, famous for its large elephant herds set against the snow-capped peak of Mount Kilimanjaro.',
                'description' => 'Renowned for large elephant herds with Mount Kilimanjaro as a backdrop. The best photographs are usually taken at sunrise, when the mountain is most likely to be visible before clouds gather. Beyond elephants, expect lions, cheetahs, buffaloes, giraffes, zebras and numerous bird species across open plains and seasonal wetlands.',
                'activities' => ['Game Drives', 'Elephant Viewing', 'Photography', 'Kilimanjaro Views'],
                'gallery' => [
                    $img('amboseli-calf.png'),
                    $img('amboseli-herd-green.png'),
                    $img('amboseli-herd-plains.png'),
                    $img('amboseli-trek.png'),
                ],
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Samburu National Reserve',
                'slug' => 'samburu',
                'region' => 'Northern Kenya',
                'location' => 'Northern Kenya',
                'region_key' => 'north',
                'tag' => 'Northern Special Five',
                'best_time' => 'Jun – Sep, Jan – Feb',
                'image' => $img('samburu.png'),
                'hero_image' => $img('samburu.png'),
                'excerpt' => 'A distinctive semi-arid reserve crossed by the Ewaso Ng\'iro River, home to wildlife found in few other parts of Kenya.',
                'intro' => 'Samburu National Reserve is one of Kenya\'s most distinctive safari destinations. Its semi-arid landscape, crossed by the Ewaso Ng\'iro River, supports wildlife found in few other parts of the country.',
                'description' => 'Home to unique northern species like Grevy\'s zebra, reticulated giraffe, and gerenuk — along with elephants, predators and rich riverine birdlife. The landscape feels remote and cinematic, with rugged hills framing the river corridors where wildlife concentrates.',
                'activities' => ['Game Drives', 'Northern Special Five', 'River Viewing', 'Cultural Visits'],
                'gallery' => [
                    $img('samburu-elephant.png'),
                    $img('samburu-buffalo.png'),
                    $img('samburu-wildebeest.png'),
                ],
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Tsavo East National Park',
                'slug' => 'tsavo-east',
                'region' => 'Coast Province',
                'location' => 'South-East Kenya',
                'region_key' => 'coast',
                'tag' => 'Red Elephants',
                'best_time' => 'Jun – Oct',
                'image' => $img('tsavo.png'),
                'hero_image' => $img('tsavo.png'),
                'excerpt' => 'One of Kenya\'s largest parks — known for red elephants and vast landscapes.',
                'intro' => 'Tsavo National Park is Kenya\'s largest protected wilderness, made up of Tsavo East National Park and Tsavo West National Park. Together, they offer some of the country\'s most diverse safari experiences.',
                'description' => 'Tsavo East is one of Kenya\'s largest parks, known for red elephants and vast landscapes. Open plains, big skies and arid beauty reward travellers who want space and wilderness. Often combined with Amboseli or the coast for a contrasting itinerary.',
                'activities' => ['Game Drives', 'Birdwatching', 'Vast Landscape Viewing'],
                'gallery' => [
                    $img('tsavo-buffalo.png'),
                    $img('tsavo-zebras.png'),
                    $img('tsavo-hills.png'),
                    $img('tsavo-landscape.png'),
                ],
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'name' => 'Tsavo West National Park',
                'slug' => 'tsavo-west',
                'region' => 'Coast Province',
                'location' => 'South-East Kenya',
                'region_key' => 'coast',
                'tag' => 'Mzima Springs',
                'best_time' => 'Jun – Oct',
                'image' => $img('tsavo.png'),
                'hero_image' => $img('tsavo.png'),
                'excerpt' => 'Mzima Springs, lava flows, and diverse wildlife in a volcanic landscape.',
                'intro' => 'Tsavo West National Park features Mzima Springs, lava flows, and diverse wildlife — a more varied landscape within Kenya\'s largest protected wilderness.',
                'description' => 'Part of Tsavo National Park — Kenya\'s largest protected wilderness together with Tsavo East. Lava fields, springs and wildlife around water sources give Tsavo West a distinct character. It pairs beautifully with Amboseli or a coastal finale.',
                'activities' => ['Game Drives', 'Mzima Springs', 'Lava Flow Views'],
                'gallery' => [
                    $img('tsavo-landscape.png'),
                    $img('tsavo-hills.png'),
                    $img('tsavo-buffalo.png'),
                    $img('tsavo-zebras.png'),
                ],
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Lake Nakuru National Park',
                'slug' => 'lake-nakuru',
                'region' => 'Rift Valley',
                'location' => 'Rift Valley',
                'region_key' => 'rift',
                'tag' => 'Rhinos & Flamingos',
                'best_time' => 'Year-round',
                'image' => $img('lake-nakuru.png'),
                'hero_image' => $img('lake-nakuru.png'),
                'excerpt' => 'A premier wildlife park famous for its alkaline lake, rhinos, and exceptional birdlife.',
                'intro' => 'Lake Nakuru National Park is one of Kenya\'s premier wildlife parks, famous for its beautiful alkaline lake, rhinos, and exceptional birdlife.',
                'description' => 'Famous for rhinos, flamingos, and scenic viewpoints. Spot black and white rhinos, Rothschild\'s giraffes, lions, leopards, and flamingos (seasonal), alongside rich birdlife along the lakeshore and forested escarpments.',
                'activities' => ['Game Drives', 'Rhino Tracking', 'Birdwatching', 'Viewpoint Visits'],
                'gallery' => [
                    $img('lake-nakuru.png'),
                    $img('lake-naivasha.png'),
                ],
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Lake Naivasha',
                'slug' => 'lake-naivasha',
                'region' => 'Rift Valley',
                'location' => 'Great Rift Valley',
                'region_key' => 'rift',
                'tag' => 'Boat Safaris',
                'best_time' => 'Year-round',
                'image' => $img('lake-naivasha.png'),
                'hero_image' => $img('lake-naivasha.png'),
                'excerpt' => 'A beautiful freshwater lake famous for birdlife, hippos, boat safaris and scenic surroundings.',
                'intro' => 'Lake Naivasha is a beautiful freshwater lake in Kenya\'s Great Rift Valley, famous for its birdlife, hippos, and scenic surroundings. It offers a mix of wildlife viewing, boat safaris, and outdoor activities.',
                'description' => 'Enjoy boat rides among hippos, exceptional birdwatching, and optional guided walking safaris at Crescent Island. A natural stop between Amboseli or Nairobi and the Maasai Mara or Lake Nakuru circuit.',
                'activities' => ['Boat Safaris', 'Birdwatching', 'Hippo Viewing', 'Crescent Island Walk'],
                'gallery' => [
                    $img('lake-naivasha.png'),
                    $img('lake-nakuru.png'),
                ],
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Hell\'s Gate National Park',
                'slug' => 'hells-gate',
                'region' => 'Rift Valley',
                'location' => 'Near Lake Naivasha, Rift Valley',
                'region_key' => 'rift',
                'tag' => 'Walk & Cycle',
                'best_time' => 'Year-round',
                'image' => $img('hells-gate.png'),
                'hero_image' => $img('hells-gate.png'),
                'excerpt' => 'Walking, cycling, dramatic cliffs, and geothermal features in the Rift Valley.',
                'intro' => 'Hell\'s Gate National Park offers walking, cycling, dramatic cliffs, and geothermal features — one of Kenya\'s most active outdoor safari experiences.',
                'description' => 'Unlike most parks where you stay in a vehicle, Hell\'s Gate is known for walking and cycling among wildlife, with towering cliffs, gorges and geothermal activity. Ideal as a day trip from Lake Naivasha.',
                'activities' => ['Walking Safaris', 'Cycling', 'Gorge Exploration', 'Geothermal Views'],
                'gallery' => [
                    $img('hells-gate-tower.png'),
                    $img('hells-gate-gorge.png'),
                    $img('hells-gate-elsa.png'),
                ],
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'name' => 'Mount Kenya',
                'slug' => 'mount-kenya',
                'region' => 'Central Highlands',
                'location' => 'Mount Kenya National Park',
                'region_key' => 'highlands',
                'tag' => 'Hiking & Climbing',
                'best_time' => 'Jan – Feb, Jul – Oct',
                'image' => $img('mount-kenya.png'),
                'hero_image' => $img('mount-kenya.png'),
                'excerpt' => 'Africa\'s second-highest mountain — ideal for hiking and climbing.',
                'intro' => 'Mount Kenya National Park is home to Africa\'s second-highest mountain, ideal for hiking and climbing amid alpine landscapes and unique highland wildlife.',
                'description' => 'A destination for adventure travellers seeking trails, summit attempts and mountain scenery. Combine with Aberdare or Meru for a highland circuit beyond the classic savannah parks.',
                'activities' => ['Hiking', 'Mountain Climbing', 'Scenic Walks', 'Highland Wildlife'],
                'gallery' => [
                    $img('mount-kenya-valley.png'),
                    $img('mount-kenya-moorland.png'),
                ],
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'Aberdare National Park',
                'slug' => 'aberdare',
                'region' => 'Central Highlands',
                'location' => 'Central Highlands',
                'region_key' => 'highlands',
                'tag' => 'Forest & Waterfalls',
                'best_time' => 'Jan – Feb, Jun – Sep',
                'image' => $img('aberdare.png'),
                'hero_image' => $img('aberdare.png'),
                'excerpt' => 'Lush mountain forests, mist-covered peaks, spectacular waterfalls, and rare wildlife.',
                'intro' => 'Aberdare National Park is one of Kenya\'s most unique national parks, known for its lush mountain forests, mist-covered peaks, spectacular waterfalls, and rare wildlife. Unlike the open savannah parks, Aberdare offers a cool, forested safari experience.',
                'description' => 'Waterfalls, forests, and mountain wildlife define this highland park. Expect a cooler climate, dense vegetation and a quieter atmosphere than Kenya\'s more famous savannah reserves.',
                'activities' => ['Forest Game Viewing', 'Waterfall Visits', 'Mountain Wildlife', 'Scenic Drives'],
                'gallery' => [
                    $img('aberdare.png'),
                    $img('samburu.png'),
                ],
                'is_featured' => false,
                'sort_order' => 10,
            ],
            [
                'name' => 'Diani Beach',
                'slug' => 'diani-beach',
                'region' => 'Kwale County',
                'location' => 'South Coast, Kwale County',
                'region_key' => 'coast',
                'tag' => 'Coastal Escape',
                'best_time' => 'Dec – Mar',
                'image' => $img('diani-beach.png'),
                'hero_image' => $img('diani-beach.png'),
                'excerpt' => 'Powdery white sand, crystal-clear turquoise waters, palm trees, and exciting water sports.',
                'intro' => 'Diani Beach is Kenya\'s most famous beach destination, celebrated for its powdery white sand, crystal-clear turquoise waters, swaying palm trees, and exciting water sports. It is an ideal destination for relaxation, adventure, and marine life.',
                'description' => 'White sand beaches, water sports, and luxury resorts make Diani the perfect safari finale or standalone beach holiday. Snorkelling, dhow trips and leisurely days by the Indian Ocean complete any Kenya itinerary.',
                'activities' => ['Beach Relaxation', 'Water Sports', 'Snorkelling', 'Dhow Cruises'],
                'gallery' => [
                    $img('diani-aerial.png'),
                    $img('diani-shore.png'),
                    $img('diani-coast.png'),
                ],
                'is_featured' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Watamu & Lamu',
                'slug' => 'watamu-lamu',
                'region' => 'North Coast',
                'location' => 'Watamu & Lamu, Kenya Coast',
                'region_key' => 'coast',
                'tag' => 'Marine & Swahili Heritage',
                'best_time' => 'Dec – Mar',
                'image' => $img('watamu-lamu.png'),
                'hero_image' => $img('watamu-lamu.png'),
                'excerpt' => 'Coral reefs, snorkeling and dolphin tours in Watamu — plus Lamu Old Town, a UNESCO World Heritage Site.',
                'intro' => 'Watamu Marine National Park offers coral reefs, snorkeling, and dolphin tours, while Lamu Old Town is a UNESCO World Heritage Site with Swahili culture and architecture. Nearby Malindi adds historic charm and beautiful beaches.',
                'description' => 'Explore Kenya\'s north coast for marine parks, reef life and Swahili heritage. Watamu is ideal for snorkeling and dolphin tours; Lamu Old Town immerses you in culture and architecture; Malindi offers historic streets and coastal beauty.',
                'activities' => ['Snorkelling', 'Dolphin Tours', 'Cultural Walks', 'Beach Time'],
                'gallery' => [
                    $img('watamu-camels.png'),
                    $img('watamu-umbrella.png'),
                    $img('watamu-resort.png'),
                    $img('watamu-palms.png'),
                ],
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'name' => 'Nairobi National Park',
                'slug' => 'nairobi-national-park',
                'region' => 'Nairobi',
                'location' => 'Nairobi, Kenya',
                'region_key' => 'city',
                'tag' => 'City Safari',
                'best_time' => 'Year-round',
                'image' => $img('nairobi-national-park.png'),
                'hero_image' => $img('nairobi-national-park.png'),
                'excerpt' => 'The only national park in the world next to a capital city — wildlife with Nairobi\'s skyline as the backdrop.',
                'intro' => 'Nairobi National Park is the only national park in the world located next to a capital city. Just a short drive from Nairobi\'s city center, it offers an incredible safari experience with the city\'s skyline as a unique backdrop.',
                'description' => 'A Nairobi City Tour offers a fascinating mix of history, culture, architecture, and local life. Whether you have half a day or a full day, there are plenty of attractions to explore — including the Giraffe Centre, David Sheldrick Wildlife Trust, Karen Blixen Museum, KICC, Nairobi National Museum, City Market, Uhuru Park and more. Perfect for arrivals, departures or a short city add-on.',
                'activities' => ['Game Drives', 'City Tours', 'Giraffe Centre', 'Elephant Orphanage', 'Museums & Markets'],
                'gallery' => [
                    $img('nairobi-national-park.png'),
                    $img('nairobi-giraffe-skyline.png'),
                    $img('nairobi-city-tour.png'),
                ],
                'is_featured' => false,
                'sort_order' => 13,
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::updateOrCreate(
                ['slug' => $destination['slug']],
                $destination
            );
        }
    }
}
